/**
 * @file screendefs.h
 * @author Phil Hilger (phil.hilger@waterlooti.com)
 * @brief
 * @version 0.1
 * @date 2021-01-31
 *
 * @copyright (c) 2021, WaterlooTI
 *
 */

#include "colors.h"

#define COMM_INDICATOR_WIDTH 12
#define COMM_INDICATOR_HEIGHT 9
#define COMM_INDICATOR_X 1
#define COMM_INDICATOR_Y 0
#define COMM_INDICATOR_RED WHITE
#define COMM_INDICATOR_YELLOW WHITE
#define COMM_INDICATOR_GREEN WHITE
#define COMM_INDICATOR_BG_COLOR MEDIUMGREY

#define TIME_INDICATOR_WIDTH 40
#define TIME_INDICATOR_HEIGHT 8
#define TIME_INDICATOR_X ((128 - TIME_INDICATOR_WIDTH) / 2)
#define TIME_INDICATOR_Y 2
#define TIME_INDICATOR_COLOR WHITE

#define BATTERY_INDICATOR_WIDTH 15
#define BATTERY_INDICATOR_HEIGHT 8
#define BATTERY_INDICATOR_X (128 - BATTERY_INDICATOR_WIDTH - 1)
#define BATTERY_INDICATOR_Y 1
#define BATTERY_COLOR_RED RED
#define BATTERY_COLOR_GREEN WHITE

#define DEFAULT_LABEL_COLOR DARKBLUE
#define DEFAULT_VALUE_COLOR WHITE

#define TOPBAR_HEIGHT 12
#define BOTTOMBAR_HEIGHT 13

#define BORDER_COLOR MEDIUMGREY

#define BG_COLOR BLACK
#define TOPBAR_BG_COLOR DARKGREY
#define BOTTOMBAR_BG_COLOR DARKGREY

#define BLINK_PERIOD_MS 1000UL
#define REFRESH_TIMER_MS 100

#define ALERT_BG_COLOR BLACK

#define PROGRESSBAR_WIDTH 64
#define PROGRESSBAR_HEIGHT 12
#define PROGRESSBAR_COLOR_1 TURQUOISE
#define PROGRESSBAR_COLOR_2 DARKBLUE
#define PROGRESSBAR_BG_COLOR BLACK
#define PROGRESSBAR_BORDER_COLOR MEDIUMGREY
#define PROGRESSBAR_RADIUS 0
#define PROGRESSBAR_SHOW_VALUE 0
#define PROGRESSBAR_TEXT_COLOR YELLOW
#define PROGRESSBAR_TEXT_SHADOW BLACK

#define ACTIVITY_WIDTH 64
#define ACTIVITY_HEIGHT 4
#define ACTIVITY_COLOR TURQUOISE
#define ACTIVITY_BG_COLOR BLACK
